### ISSUE TITLE
Fork terra-money packages

### ISSUE THREAD

**Issue by geoffmunn** [terra-rebels/station-extension#16]
We need to fork the terra-money packages.

Specifically, these ones:

-  @terra-money/ledger-terra-js (current version: 1.3.0)
-  @terra-money/log-finder-ruleset (current version: 3.0.2)
-  @terra-money/msg-reader (current version: 3.0.1)
-  @terra-money/terra.js (current version: 3.1.7)
-  @terra-money/terra.proto (current version: 2.0.0)
-  @terra-money/wallet-provider (current version: 3.11.0)

With the two projects now going completely separate ways, it is unsafe to rely on the terra-money codebase. Also, this will allow us to make improvements and fix bugs.

This is also an issue for the station repo.

**Comment by geoffmunn** [comment]
This is a substep in issue #8, but no progress has been officially made and this is a significant problem.

**Comment by echel0n-TR** [comment]
all packages have already been forked, updated, and pushed to npmjs
